# Generated by Django 4.0.1 on 2022-01-31 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_plan_end_date_profile_plan_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('provider_order_id', models.CharField(max_length=40)),
                ('payment_id', models.CharField(max_length=36)),
                ('signature_id', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
