# Generated by Django 4.0.1 on 2022-02-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile_keydir_alter_profile_bucket_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='keydir',
            field=models.TextField(blank=True),
        ),
    ]
