# Generated by Django 4.0.1 on 2022-02-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_profile_keydir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='storage_limit',
            field=models.BigIntegerField(default=5368709120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='storage_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
